version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: apexliftdb
      POSTGRES_USER: apexlift
      POSTGRES_PASSWORD: apexlift123
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn apexliftstudio.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://apexlift:apexlift123@db:5432/apexliftdb
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: